export const SET_DEVICE = 'SET_DEVICE';
export const CLEAR_DEVICE = 'CLEAR_DEVICE';

export const ADD_ADVERTISING_DEVICE = 'ADD_ADVERTISING_DEVICE';
export const REMOVE_ADVERTISING_DEVICE = 'REMOVE_ADVERTISING_DEVICE';
export const CLEAR_ADVERTISING_DEVICES = 'CLEAR_ADVERTISING_DEVICES';

export const ADD_SPOTCHECK_READING = 'ADD_SPOTCHECK_READING';
export const CLEAR_SPOTCHECK_READINGS = 'CLEAR_SPOTCHECK_READINGS';

export const ADD_CONTINUOUSCHECK_READING = 'ADD_CONTINUOUSCHECK_READING';
export const CLEAR_CONTINUOUSCHECK_READINGS = 'CLEAR_CONTINUOUSCHECK_READINGS';

export const TOGGLE_SCANNING = 'TOGGLE_SCANNING';
export const TOGGLE_CONNECTED = 'TOGGLE_CONNECTED';
export const TOGGLE_ENCRYPTED = 'TOGGLE_ENCRYPTED';
export const TOGGLE_LOW_BATTERY = 'TOGGLE_LOW_BATTERY';
export const TOGGLE_MONITORING = 'TOGGLE_MONITORING';
export const TOGGLE_SYNCING = 'TOGGLE_SYNCING';
export const TOGGLE_SYNCED = 'TOGGLE_SYNCED';
export const RESET_CONNECTION_STATE = 'RESET_CONNECTION_STATE';